BristolSTA/uobtheatre-web

.github/workflows/test.yml
tests/e2e/specs/test.js

Implement GitHub Actions

---

.devcontainer/docker-compose.yml
config.js
nuxt.config.js
package.json
plugins/initial-auth.js
services/authService.js
tests/unit/components/AuthBox.spec.js
yarn.lock

Fixes API authentication to use the refresh token as required

fix: API Authentication 

---

.eslintrc.js
assets/styles/app.scss
classes/Errors.js
components/auth/UserAuthBox.vue
errors/ValidationError.js
errors/auth/UnverifiedLoginError.js
graphql/partials/ErrorsPartial.js
package.json
services/authService.js
tests/unit/classes/Errors.spec.js
tests/unit/components/AuthBox.spec.js
tests/unit/fixtures/support/GenericError.js
tests/unit/helpers.js
tests/unit/pages/booking/Book.spec.js
tests/unit/pages/booking/stages/PaymentStage.spec.js
tests/unit/pages/booking/stages/TicketSelectionStage.spec.js
utils.js
yarn.lock

feat: Email Verification Re-request

---

components/ui/Carousel.vue
pages/index.vue
pages/publicity-screen.vue
tests/unit/components/ui/Carousel.spec.js
tests/unit/pages/Home.spec.js

Updating the carousel component and publicity screen

Even more fixes

---

components/booking/SeatGroup.vue

ticket prices in acending order

---

pages/index.vue
tests/unit/pages/Home.spec.js

fix: Homepage carousel same date

---

components/box-office/BookingRow.vue
components/performance/TimeGroupedPerformanceSelector.vue
components/production/ProductionPerformances.vue
graphql/fragments/booking/DetailedBookingDetails.gql
graphql/queries/admin/productions/AdminPerformancesIndex.gql
graphql/queries/box-office/BoxOfficePerformanceBooking.gql
pages/administration/productions/_productionSlug/index.vue

Production features

---

.vscode/tasks.json
components/performance/editor/PriceMatrix.vue
pages/administration.vue

fix: Price matrix update on seat group price change

---

components/box-office/Overview.vue
pages/box-office/_performanceId/sell/complete.vue

fix/not auto check-in box office sold ticket

---

pages/publicity-screen/[venueSlugs]/index.vue

instead of installing some dumb 3rd party app, just use this

Make mouse auto hide automatically

---

pages/publicity-screen/[venueSlugs]/index.vue

Reverts BristolSTA/uobtheatre-web#329

Revert "Make mouse auto hide automatically"

---

components/box-office/Booking/BoxOfficeBookingHeader.vue
components/box-office/Booking/BoxOfficeBookingInspector.vue
components/box-office/Booking/BoxOfficeBookingList.vue
components/box-office/BoxOfficeCheckInProgress.vue
components/box-office/Sell/BoxOfficeSellPaymentCard.vue
pages/box-office/[performanceId]/index.vue
pages/box-office/[performanceId]/sell/complete.vue
pages/box-office/[performanceId]/sell/index.vue
pages/box-office/index.vue
types/generic.d.ts

feat: Box Office Tweaks and Fixes

---

classes/Ticket.ts
pages/administration/productions/[productionSlug]/bookings/[bookingReference]/index.vue

Functional & tested, but I'm sure not the finest code you've ever seen. If it can be simplified poke me in the right direction :p

feat: Implement Checked In At / Checked In By (Closes #294) on Admin Booking Inspection

---

pages/administration/productions/[productionSlug]/bookings/[bookingReference]/index.vue

Fixes overflow problem on mobile with the new ticket inspection window

fix: Make Ticket Inspection window a Paginated Table

---

components/production/editor/ProductionEditor.vue

Tested locally, fixing the typo resolves the problem

fix: Resolves #348 preventing a production's slug from being edited due to a typo

---

components/production/ProductionDraftWarningBanner.vue
graphql/queries/ProductionBySlug.gql
pages/production/[slug]/book.vue
pages/production/[slug]/index.vue
tests/unit/components/production/ProductionDraftWarningBanner.spec.js
tests/unit/pages/production/Production.spec.js
tests/unit/support/fixtures/Production.js

feat: Draft production warning banner

---

components/booking/BookingHomepageOverview.vue
components/layout/LayoutNavBar.vue
components/ui/Input/ImageInput.vue
components/ui/UiStaButton.vue
components/user/UserDetails.vue
graphql/queries/user/UpcomingBookings.gql
package.json
pages/index.vue
tests/unit/components/booking/BookingHomepageOverview.spec.js
tests/unit/pages/Home.spec.js
tests/unit/support/fixtures/Venue.js
tests/unit/support/helpers/mount.ts

feat: user upcoming bookings on homepage

---

components/layout/LayoutNavBar.vue
components/performance/editor/PerformanceEditor.vue
components/performance/editor/PriceMatrix.vue
components/production/ProductionBanner.vue
nuxt.config.ts
package.json
tests/unit/components/production/ProductionBanner.spec.js
yarn.lock

Clean up language about production descriptions, make seat group warnings clearer, restyle concession types to ticket types, add an info tooltip for fees

fix/feat: Clean up some confusing language, add an info tooltip to explain our fees

---

components/admin/AdminSidebar.vue
components/box-office/Booking/BoxOfficeBookingTickets.vue
components/user/UserDetails.vue
middleware/finance.ts
pages/administration/finance-reports.vue
pages/administration/index.vue
pages/administration/productions/[productionSlug]/index.vue
pages/administration/productions/[productionSlug]/performances/[performanceId]/index.vue

Hide the buttons, introduce a middleware to redirect away if no perms, fix some other seperate table issues. Resolves #356

fix: Hide 'Finance Reports' in admin panel if user doesn't have finance perms

---

components/admin/permissions/PermissionsAssigner.vue
pages/administration/productions/[productionSlug]/permissions.vue
tests/unit/pages/admin/ProductionPermissions.spec.js
tests/unit/support/fixtures/ProductionPermissions.js

Resolves #659. Also introduces a test to make sure the page is functioning properly in the future.

fix: Fix Production Permission Assigner Fatal Errors

---

classes/Ticket.ts
components/ui/Input/UiInputTicketScanner.client.vue
composables/useHardwareTicketScanner.ts
pages/box-office/[performanceId]/index.vue
tests/unit/classes/Ticket.spec.js

This fixes the issue with the QR code scanner, ever since the vue QR input scanner started returning objects rather than strings. See the documentation below for information.
Also shows that we need new unit tests for this area!
- [Documentation](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#decode)
- Resolves #721

Fix QR code scanner

---

assets/styles/app.scss

Fix some upcoming SASS depreciation issues

fix: Fix SASS deprecation warnings

---

components/production/editor/ProductionEditor.vue
graphql/queries/HomeUpcomingProductions.gql
graphql/queries/admin/productions/AdminProductionEdit.gql
pages/index.vue
pages/production/[slug]/index.vue
tests/unit/pages/Home.spec.js

Production excerpts frount end stuff

feat: Excerpts for productions

---

package.json
yarn.lock

fix: Regress @nuxt/ui to fixed 2.22.0 due to @nuxtjs/tailwindcss not yet having the tailwindcss v4 support required for @nuxt/ui v3+

Web Release v1.2.5a

---

components/production/ProductionOverview.vue
components/production/content-warnings/ContentWarningDisplay.vue
components/production/content-warnings/ContentWarningsDisplay.vue
pages/production/[slug]/book/[performanceId]/overview.vue
pages/production/[slug]/book/[performanceId]/pay.vue
pages/production/[slug]/book/[performanceId]/tickets.vue
pages/production/[slug]/book/[performanceId]/warnings.vue
tests/unit/components/production/ProductionOverview.spec.js
tests/unit/pages/booking/stages/AudienceWarningsStage.spec.js

- Changes content warning text
- Moves content warnings modal from ProductionOverview component into its own components
- Display production warnings separately in the production information
- Update booking flow warnings for changes
resolves #765

Update content warnings

---

components/production/ProductionBanner.vue
tests/unit/components/production/ProductionBanner.spec.js
utils/datetime.ts

small change to the way we round timings to be to 15 minutes instead of 1 hour

fix: round timings to nearest 15 minutes
